version: "3"

services:
  ##ref: https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/README.md
  nginx:
    build: .
    container_name: streaming-server-in-a-bottle
    ports:
      - "1935:1935/tcp"
    volumes:
      - ./nginxconf:/usr/local/nginx/conf

    # environment:
    restart: always
    # nginx by default run in daemon mode, thus without the option, exit(0); which will then always trigger a container restart.
    command: ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]
